sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
script:
  - yarn test
  - yarn build
after_success:
  - yarn semantic-release
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
      then yarn gh-pages -d _book -r https://$GH_TOKEN@github.com/axelyung/yarfl.git;
    fi
branches:
  only:
    - master
    - next
